# Debugging Hints

[AMath 586, Spring Quarter 2016](http://faculty.washington.edu/rjl/classes/am586s2016/)

The Python [pdb module](https://docs.python.org/2/library/pdb.html) is useful for debugging Python code.  

This notebook shows a simple example.

In [3]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [4]:
from scipy.linalg import expm

The code below is supposed to solve $u'(t) = Iu(t)$ with $u(0) = \eta$ in the $5\times 5$ case where $I$ is the identity matrix and all elements of $\eta$ are equal to 1. 

In [7]:
def utrue(t):
    # Solve u'(t) = A u(t) with A = I, u(0) = eta
    A = eye(5)   # 5x5 identity matrix
    eta = array([1.,1.,1.,1.])
    u = dot(expm(A*t),eta)
    return u

In [8]:
utrue(1.)

ValueError: shapes (5,5) and (4,) not aligned: 5 (dim 1) != 4 (dim 0)

The error message above doesn't give much information about where the error occurred.  

We can get more information by turning on the pdb debugger, using the Jupyter "magic" command `pdb`.  If you execute this a second time, it turns the debugger off.

In [10]:
pdb

Automatic pdb calling has been turned ON


In [11]:
utrue(1.)

ValueError: shapes (5,5) and (4,) not aligned: 5 (dim 1) != 4 (dim 0)

> <ipython-input-7-84243fc44f8b>(5)utrue()
      4     eta = array([1.,1.,1.,1.])
----> 5     u = dot(expm(A*t),eta)
      6     return u

ipdb> print eta.shape
(4,)
ipdb> print A.shape
(5, 5)
ipdb> q


Note that it now tells what line the error occurred and gives a `ipdb>` prompt.  You can query the state of variable, e.g. by typing a print statement and then hitting Shift-Enter.  Type `q` and Shift-Enter to quit (which you have to do before you can execute any other cell).

In [14]:
pdb

Automatic pdb calling has been turned OFF


You can also put in a breakpoint to probe the state at some point, even if it is not giving an error.  Here's a corrected version of the code with a breakpoint added.

In [15]:
from pdb import set_trace

def utrue(t):
    # Solve u'(t) = A u(t) with A = I, u(0) = eta
    A = eye(5)   # 5x5 identity matrix
    eta = array([1.,1.,1.,1.,1.])
    u = dot(expm(A*t),eta)
    set_trace()  # breakpoint here
    return u

In [16]:
utrue(1.)

> <ipython-input-15-d2a133b9f22f>(9)utrue()
-> return u
(Pdb) print u
[ 2.71828183  2.71828183  2.71828183  2.71828183  2.71828183]
(Pdb) print A
[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]
(Pdb) c


array([ 2.71828183,  2.71828183,  2.71828183,  2.71828183,  2.71828183])

You can end the `(Pdb)` prompt with `q` to quit, or if things are working right, with `c` to continue executing from this point.  

If you happen to delete a cell when it's waiting for pdb input and the notebook hangs, remember that you can select `Interrupt` from the `Kernel` menu.